ZO_CreateStringId("SI_BINDING_NAME_GREET", "Grüße")
ZO_CreateStringId("SI_BINDING_NAME_HELLO", "Hallo")
ZO_CreateStringId("SI_BINDING_NAME_THANKS", "Danke")
ZO_CreateStringId("SI_BINDING_NAME_LAUGH", "Lachen")
ZO_CreateStringId("SI_BINDING_NAME_YAWN", "Müde")
ZO_CreateStringId("SI_BINDING_NAME_GRATS", "Begeisterung")
ZO_CreateStringId("SI_BINDING_NAME_CONGRATULATE", "Gratulation")
ZO_CreateStringId("SI_BINDING_NAME_WELCOME", "Willkommen")
ZO_CreateStringId("SI_BINDING_NAME_YES", "Ja")
ZO_CreateStringId("SI_BINDING_NAME_NO", "Nein")
ZO_CreateStringId("SI_BINDING_NAME_NOD", "Nicken")
ZO_CreateStringId("SI_BINDING_NAME_THUMBSUP", "Daumen hoch")
ZO_CreateStringId("SI_BINDING_NAME_SIGH", "Seufzen")
ZO_CreateStringId("SI_BINDING_NAME_CROUCH", "Hocken")
ZO_CreateStringId("SI_BINDING_NAME_STRETCH", "Strecken")
ZO_CreateStringId("SI_BINDING_NAME_RELOADUI", "Reload UI")
ZO_CreateStringId("SI_BINDING_NAME_SALUTE", "Salutieren")
ZO_CreateStringId("SI_BINDING_NAME_ISEEYOU", "Ich seh Dich")
ZO_CreateStringId("SI_BINDING_NAME_SWORDDANCE", "Schwerttanz")
