ZO_CreateStringId("SI_BINDING_NAME_GREET", "Greet")
ZO_CreateStringId("SI_BINDING_NAME_HELLO", "Hello")
ZO_CreateStringId("SI_BINDING_NAME_THANKS", "Thanks")
ZO_CreateStringId("SI_BINDING_NAME_LAUGH", "Laugh")
ZO_CreateStringId("SI_BINDING_NAME_YAWN", "Yawn")
ZO_CreateStringId("SI_BINDING_NAME_GRATS", "Grats")
ZO_CreateStringId("SI_BINDING_NAME_CONGRATULATE", "Congratulate")
ZO_CreateStringId("SI_BINDING_NAME_WELCOME", "Welcome")
ZO_CreateStringId("SI_BINDING_NAME_YES", "Yes")
ZO_CreateStringId("SI_BINDING_NAME_NO", "No")
ZO_CreateStringId("SI_BINDING_NAME_NOD", "Nod")
ZO_CreateStringId("SI_BINDING_NAME_THUMBSUP", "Thumbs Up")
ZO_CreateStringId("SI_BINDING_NAME_SIGH", "Sigh")
ZO_CreateStringId("SI_BINDING_NAME_CROUCH", "Crouch")
ZO_CreateStringId("SI_BINDING_NAME_STRETCH", "Stretch")
ZO_CreateStringId("SI_BINDING_NAME_RELOADUI", "Reload UI")
ZO_CreateStringId("SI_BINDING_NAME_SALUTE", "Salute")
ZO_CreateStringId("SI_BINDING_NAME_ISEEYOU", "I See You")
ZO_CreateStringId("SI_BINDING_NAME_SWORDDANCE", "Sword Dance")
