PotMaker:LoadLanguage {
	name = "jp",

	-- check_all = "全てチェック",
	-- uncheck_all = "全てのチェックを外す",
	search = "検索",
	search_again = "戻る",
	only = "選択した試料のみ使用する",
	potion2reagents = "2つの試料だけを使って薬を作る",
	questpotionsonly = "クエストの条件に限った薬",
	need_solvent = "溶媒が必要",
	search_results = "検索結果",
	combinations = "試料の組み合わせ",
	favorites = "お気に入り",
	mark_favorite = "お気に入りとしてマークする",
	unmark_favorite = "お気に入りから外す",
	skill = "スキル",
	settings_short = "設定",
	settings_enableBtn = "ESOインターフェースの表示/非表示ボタン",
	use_missing_reagents_short = "見つからない試料を含む",
	use_missing_reagents_long = "持っていない試料を使う薬を検索するにはこれをチェックする",
	use_missing_reagents_warning = "これを有効にすると表に試料を自動的に追加する機能がオフになります！",
	use_unknown_traits_short = "検索に不明な特性を含める",
	use_unknown_traits_long = "検索に不明な特性を含めるにはこれをチェックする",
	fake_third_slot_short = "3番目のスロットがアンロックされているように見せかける",
	fake_third_slot_long = "まるで試料のための3つの錬金術スロットを持っているかのように検索を実行するにはこれをチェックする",
	training_short = "不明な特色のみ",
	training_long = "新しい知られた特色の結果のみで錬金術を行う",
	training_warning = "これは新しい特色を学習しない全ての結果を隠します！",
	same_window_coords_short = "同じ位置の窓",
	same_window_coords_long = "検索窓と同じ位置に結果窓を表示するにはこれをチェックする",
	show_xp_short = "経験値を表示",
	show_xp_long = "得られる錬金術の経験値に関するシステムメッセージを表示する",
	reagent_stackorder_short = "数量で並び替えられた試料",
	reagent_stackorder_long = "名前代わりに数量で試料を並び替えします",
	show_favorite_header = "お気に入り",
	show_favorite_short = "リスト",
	show_favorite_long = "マークされた試料：マークのみ\n同じ薬：同じ薬の組み合わせ\n同じ特色：全てのレベルの同じ特性の薬",
	show_favorite_reagents = "マークされた試料",
	show_favorite_potion = "同じ薬",
	show_favorite_traits = "同じ特色",
	filter_favorite_traits = "特色で絞る",
	filter_favorite_solvents = "溶媒で絞る",
	filter_favorite_reagents = "試料で絞る",
	show_mainmenu_item_short = "メインメニューのアイテムを表示",
	show_mainmenu_item_long = "Potion Makerに切り替えるためのメインメニューのアイテム。変更はユーザーインタフェースの再起動後に反映されます。",
	show_as_default = "Potion Makerをデフォルトにする",
	show_as_default_long = "錬金台で自動的にPotionMakerのタブを選択する",
	item_saver_header = "FCOItemSaver & ItemSaver",
	use_item_saver = "(FCO)ItemSaverを使用する",
	use_item_saver_long = "FCOItemSaver または ItemSaver のアドオンによってマークされた溶媒/成分を使用しない",
	item_saver_protected = "アイテムは保護されています",
	suppress_new_trait_dialog = "新しい特色のポップアップを隠す",
	suppress_new_trait_dialog_long = "発見した特色のポップアップダイアログの代わりにアナウンスを表示する",

	traitNames =
	{
		["Restore Health"] = "体力回復",
		["Ravage Health"] = "体力減少",
		["Restore Magicka"] = "マジカ回復",
		["Ravage Magicka"] = "マジカ減少",
		["Restore Stamina"] = "スタミナ回復",
		["Ravage Stamina"] = "スタミナ減少",
		["Increase Weapon Power"] = "武器攻撃力上昇",
		["Lower Weapon Power"] = "不自由",
		["Increase Spell Power"] = "呪文攻撃力上昇",
		["Lower Spell Power"] = "臆病",
		["Weapon Crit"] = "武器クリティカル",
		["Lower Weapon Crit"] = "弱体化",
		["Spell Crit"] = "呪文クリティカル",
		["Lower Spell Crit"] = "不信",
		["Increase Armor"] = "防御力増大",
		["Lower Armor"] = "破砕",
		["Increase Spell Resist"] = "呪文耐性増大",
		["Lower Spell Resist"] = "侵害",
		["Unstoppable"] = "猪突猛進",
		["Stun"] = "罠",
		["Speed"] = "加速",
		["Reduce Speed"] = "妨害",
		["Invisible"] = "透明化",
		["Detection"] = "探知",

		["Sustained Restore Health"] = "体力継続",
		["Creeping Ravage Health"] = "体力漸減",
		["Vitality"] = "生命力",
		["Vulnerability"] = "脆弱",
		["Protection"] = "防護",
		["Defile"] = "汚染",
	},

}

SafeAddString(SI_BINDING_NAME_POTIONMAKER, "ポーション作成")
SafeAddString(SI_BINDING_NAME_POISONMAKER, "毒作成")
