--     Russian translation by @KiriX    --
--		UPD by Memoraike		--
--		UPD by canadagreen		--
PotMaker:LoadLanguage {
	name = "ru",
--	check_all = "Выбрать все",
--	uncheck_all = "Отменить выбор",
	search = "Поиск",
	search_again = "Назад",
	only = "Только выбранное",
	potion2reagents = "Делать зелья и яды только из 2 реагентов",
	questpotionsonly = "Зелья и яды для заданий",
	need_solvent = "Нужен растворитель",
	search_results = "Результаты поиска",
	combinations = "Комбинации реагентов",
	favorites = "Избранное",
	mark_favorite = "В избранное",
	unmark_favorite = "Из избранного",
	skill = "Навык",
	settings_short = "Настройки",
	settings_enableBtn = "Кнопка Скрыть/показать в игровом интерфейсе",
	use_missing_reagents_short = "Отсутствующие реагенты",
	use_missing_reagents_long = "Отметьте, чтобы искать зелья, даже если у вас нет какого-то реагента для них.",
	use_missing_reagents_warning = "Включение этой функции отключает автоматическое добавление реагентов на стол!",
	use_unknown_traits_short = "Неизвестные эффекты",
	use_unknown_traits_long = "Отметьте, чтобы включать в поиск ещё неизвестные вам эффекты реагентов.",
	fake_third_slot_short = "Имитация третьего слота",
	fake_third_slot_long = "Отметьте, чтобы поиск работал, если у вас имеется три слота для реагентов.",
	training_short = "Только неизвестные эффекты",
	training_long = "Поиск будет выдавать только те результаты, где вы сможете открыть новые, не известные ещё эффекты.",
	training_warning = "Это скроет все результаты, где вы не откроете новых эффектов!",
	same_window_coords_short = "Результаты в том же положении",
	same_window_coords_long = "Отметьте, чтобы окно результатов появлялось в том же месте, что и окно поиска.",
	show_xp_short = "Показывать XP",
	show_xp_long = "Показывает системное сообщение для опыта, получаемого в алхимии",
	reagent_stackorder_short = "Сортировка по качеству",
	reagent_stackorder_long = "Сортирует реагенты по качеству, вместо сортировки на названию.",
	show_favorite_header = "Избранное",
	show_favorite_short = "Список",
	show_favorite_long = "Помеченные реагенты: только отмеченные\nОдинаковые зелья: Комбинации, получающие одни и те же зелья\nSОдинаковые эффекты: Зелья с одинаковыми эффектами любого уровня",
	show_favorite_reagents = "Помеченные реагенты",
	show_favorite_potion = "Те же зелья",
	show_favorite_traits = "Те же эффекты",
	filter_favorite_traits = "Фильтровать по эффектам",
	filter_favorite_solvents = "Фильтровать по растворителям",
	filter_favorite_reagents = "Фильтровать по реагентам",
	show_mainmenu_item_short = "Отобразить иконку",
	show_mainmenu_item_long = "Отображает иконку аддона в меню персонажа.",
	show_as_default = "Аддон по умолчанию",
	show_as_default_long = "При открытии алхимической станции будет выбрано меню аддона.",
	item_saver_header = "FCOItemSaver & ItemSaver",
	use_item_saver = "Использовать (FCO)ItemSaver",
	use_item_saver_long = "Запрещает использовать реагенты/растворители помеченные аддоном FCOItemSaver.",
	item_saver_protected = "Заблокированный предмет.",

	traitNames =
	{
		["Restore Health"] = "Восстановление здоровья",
		["Ravage Health"] = "Опустошение здоровья",
		["Restore Magicka"] = "Восстановление магии",
		["Ravage Magicka"] = "Опустошение магии",
		["Restore Stamina"] = "Восстановление запаса сил",
		["Ravage Stamina"] = "Опустошение запаса сил",
		["Increase Weapon Power"] = "Увеличение силы оружия",
		["Lower Weapon Power"] = "Травма",
		["Increase Spell Power"] = "Увеличение силы заклинаний",
		["Lower Spell Power"] = "Трусость",
		["Weapon Crit"] = "Крит. рейтинг оружия",
	    ["Lower Weapon Crit"] = "Бессилие",
		["Spell Crit"] = "Крит. рейтинг заклинаний",
		["Lower Spell Crit"] = "Неуверенность",
		["Increase Armor"] = "Увеличение показателя брони",
		["Lower Armor"] = "Перелом",
		["Increase Spell Resist"] = "Увеличение магической сопротивляемости",
		["Lower Spell Resist"] = "Прорыв",
		["Unstoppable"] = "Неудержимость",
		["Stun"] = "Захват",
		["Speed"] = "Скорость",
		["Reduce Speed"] = "Замедление",
		["Invisible"] = "Невидимость",
		["Detection"] = "Обнаружение",
		["Sustained Restore Health"] = "Длительное исцеление",
		["Creeping Ravage Health"] = "Постепенное опустошение здоровья",
		["Vitality"] = "Живучесть",
		["Vulnerability"] = "Уязвимость",
		["Protection"] = "Защита",
		["Defile"] = "Осквернение",

		["Heroism"] = "Героизм",
		["Timidity"] = "Трусливость",
	},
}
