local addon = VOTANS_IMPROVED_OUTFIT

VOTAN_DYEING_SORT_STYLE_MATERIAL = 1231
VOTAN_DYEING_MATERIAL_MATT = 1
VOTAN_DYEING_MATERIAL_POLISHED = 2
VOTAN_DYEING_MATERIAL_METALLIC = 3
VOTAN_DYEING_MATERIAL_UNCLASSIFIED = 4

local VOTAN_DYEING_MATERIAL_MATT, VOTAN_DYEING_MATERIAL_POLISHED, VOTAN_DYEING_MATERIAL_METALLIC = VOTAN_DYEING_MATERIAL_MATT, VOTAN_DYEING_MATERIAL_POLISHED, VOTAN_DYEING_MATERIAL_METALLIC

local VOTAN_DYEING_SORT_STYLE_MATERIAL = VOTAN_DYEING_SORT_STYLE_MATERIAL
-- ZO_DYEING_MANAGER

local dyeIdToMateral = {
	[5] = VOTAN_DYEING_MATERIAL_MATT,
	[15] = VOTAN_DYEING_MATERIAL_MATT,
	[16] = VOTAN_DYEING_MATERIAL_MATT,
	[21] = VOTAN_DYEING_MATERIAL_MATT,
	[29] = VOTAN_DYEING_MATERIAL_MATT,
	[30] = VOTAN_DYEING_MATERIAL_MATT,
	[31] = VOTAN_DYEING_MATERIAL_MATT,
	[38] = VOTAN_DYEING_MATERIAL_MATT,
	[46] = VOTAN_DYEING_MATERIAL_MATT,
	[53] = VOTAN_DYEING_MATERIAL_MATT,
	[62] = VOTAN_DYEING_MATERIAL_MATT,
	[69] = VOTAN_DYEING_MATERIAL_MATT,
	[70] = VOTAN_DYEING_MATERIAL_MATT,
	[77] = VOTAN_DYEING_MATERIAL_MATT,
	[80] = VOTAN_DYEING_MATERIAL_MATT,
	[85] = VOTAN_DYEING_MATERIAL_MATT,
	[87] = VOTAN_DYEING_MATERIAL_MATT,
	[88] = VOTAN_DYEING_MATERIAL_MATT,
	[101] = VOTAN_DYEING_MATERIAL_MATT,
	[102] = VOTAN_DYEING_MATERIAL_MATT,
	[103] = VOTAN_DYEING_MATERIAL_MATT,
	[109] = VOTAN_DYEING_MATERIAL_MATT,
	[110] = VOTAN_DYEING_MATERIAL_MATT,
	[111] = VOTAN_DYEING_MATERIAL_MATT,
	[125] = VOTAN_DYEING_MATERIAL_MATT,
	[149] = VOTAN_DYEING_MATERIAL_MATT,
	[150] = VOTAN_DYEING_MATERIAL_MATT,
	[152] = VOTAN_DYEING_MATERIAL_MATT,
	[157] = VOTAN_DYEING_MATERIAL_MATT,
	[175] = VOTAN_DYEING_MATERIAL_MATT,
	[176] = VOTAN_DYEING_MATERIAL_MATT,
	[199] = VOTAN_DYEING_MATERIAL_MATT,
	[222] = VOTAN_DYEING_MATERIAL_MATT,
	[223] = VOTAN_DYEING_MATERIAL_MATT,
	[229] = VOTAN_DYEING_MATERIAL_MATT,
	[247] = VOTAN_DYEING_MATERIAL_MATT,
	[248] = VOTAN_DYEING_MATERIAL_MATT,
	[253] = VOTAN_DYEING_MATERIAL_MATT,
	[271] = VOTAN_DYEING_MATERIAL_MATT,
	[277] = VOTAN_DYEING_MATERIAL_MATT,
	[279] = VOTAN_DYEING_MATERIAL_MATT,
	[294] = VOTAN_DYEING_MATERIAL_MATT,
	[295] = VOTAN_DYEING_MATERIAL_MATT,
	[303] = VOTAN_DYEING_MATERIAL_MATT,
	[319] = VOTAN_DYEING_MATERIAL_MATT,
	[325] = VOTAN_DYEING_MATERIAL_MATT,
	[343] = VOTAN_DYEING_MATERIAL_MATT,
	[349] = VOTAN_DYEING_MATERIAL_MATT,
	[352] = VOTAN_DYEING_MATERIAL_MATT,
	[365] = VOTAN_DYEING_MATERIAL_MATT,
	[374] = VOTAN_DYEING_MATERIAL_MATT,
	[375] = VOTAN_DYEING_MATERIAL_MATT,
	[398] = VOTAN_DYEING_MATERIAL_MATT,
	[413] = VOTAN_DYEING_MATERIAL_MATT,
	[414] = VOTAN_DYEING_MATERIAL_MATT,
	[415] = VOTAN_DYEING_MATERIAL_MATT,
	[416] = VOTAN_DYEING_MATERIAL_MATT,
	[422] = VOTAN_DYEING_MATERIAL_MATT,
	[423] = VOTAN_DYEING_MATERIAL_MATT,
	[437] = VOTAN_DYEING_MATERIAL_MATT,
	[438] = VOTAN_DYEING_MATERIAL_MATT,
	[439] = VOTAN_DYEING_MATERIAL_MATT,
	[440] = VOTAN_DYEING_MATERIAL_MATT,
	[447] = VOTAN_DYEING_MATERIAL_MATT,
	[461] = VOTAN_DYEING_MATERIAL_MATT,
	[462] = VOTAN_DYEING_MATERIAL_MATT,
	[463] = VOTAN_DYEING_MATERIAL_MATT,
	[464] = VOTAN_DYEING_MATERIAL_MATT,
	[470] = VOTAN_DYEING_MATERIAL_MATT,
	[471] = VOTAN_DYEING_MATERIAL_MATT,
	[472] = VOTAN_DYEING_MATERIAL_MATT,
	[485] = VOTAN_DYEING_MATERIAL_MATT,
	[486] = VOTAN_DYEING_MATERIAL_MATT,
	[487] = VOTAN_DYEING_MATERIAL_MATT,
	[488] = VOTAN_DYEING_MATERIAL_MATT,
	[493] = VOTAN_DYEING_MATERIAL_MATT,
	[496] = VOTAN_DYEING_MATERIAL_MATT,
	[510] = VOTAN_DYEING_MATERIAL_MATT,
	[511] = VOTAN_DYEING_MATERIAL_MATT,
	[517] = VOTAN_DYEING_MATERIAL_MATT,
	[518] = VOTAN_DYEING_MATERIAL_MATT,
	[524] = VOTAN_DYEING_MATERIAL_MATT,
	[585] = VOTAN_DYEING_MATERIAL_MATT,
	[586] = VOTAN_DYEING_MATERIAL_MATT,
	[587] = VOTAN_DYEING_MATERIAL_MATT,
	[453] = VOTAN_DYEING_MATERIAL_MATT,
	[429] = VOTAN_DYEING_MATERIAL_MATT,
	[478] = VOTAN_DYEING_MATERIAL_MATT,
	[502] = VOTAN_DYEING_MATERIAL_MATT,
	[525] = VOTAN_DYEING_MATERIAL_MATT,
	[526] = VOTAN_DYEING_MATERIAL_MATT,
	[13] = VOTAN_DYEING_MATERIAL_POLISHED,
	[19] = VOTAN_DYEING_MATERIAL_POLISHED,
	[23] = VOTAN_DYEING_MATERIAL_POLISHED,
	[24] = VOTAN_DYEING_MATERIAL_POLISHED,
	[47] = VOTAN_DYEING_MATERIAL_POLISHED,
	[68] = VOTAN_DYEING_MATERIAL_POLISHED,
	[71] = VOTAN_DYEING_MATERIAL_POLISHED,
	[85] = VOTAN_DYEING_MATERIAL_POLISHED,
	[86] = VOTAN_DYEING_MATERIAL_POLISHED,
	[93] = VOTAN_DYEING_MATERIAL_POLISHED,
	[94] = VOTAN_DYEING_MATERIAL_POLISHED,
	[95] = VOTAN_DYEING_MATERIAL_POLISHED,
	[104] = VOTAN_DYEING_MATERIAL_POLISHED,
	[120] = VOTAN_DYEING_MATERIAL_POLISHED,
	[134] = VOTAN_DYEING_MATERIAL_POLISHED,
	[135] = VOTAN_DYEING_MATERIAL_POLISHED,
	[136] = VOTAN_DYEING_MATERIAL_POLISHED,
	[140] = VOTAN_DYEING_MATERIAL_POLISHED,
	[142] = VOTAN_DYEING_MATERIAL_POLISHED,
	[183] = VOTAN_DYEING_MATERIAL_POLISHED,
	[186] = VOTAN_DYEING_MATERIAL_POLISHED,
	[201] = VOTAN_DYEING_MATERIAL_POLISHED,
	[207] = VOTAN_DYEING_MATERIAL_POLISHED,
	[213] = VOTAN_DYEING_MATERIAL_POLISHED,
	[239] = VOTAN_DYEING_MATERIAL_POLISHED,
	[256] = VOTAN_DYEING_MATERIAL_POLISHED,
	[263] = VOTAN_DYEING_MATERIAL_POLISHED,
	[276] = VOTAN_DYEING_MATERIAL_POLISHED,
	[280] = VOTAN_DYEING_MATERIAL_POLISHED,
	[281] = VOTAN_DYEING_MATERIAL_POLISHED,
	[283] = VOTAN_DYEING_MATERIAL_POLISHED,
	[287] = VOTAN_DYEING_MATERIAL_POLISHED,
	[288] = VOTAN_DYEING_MATERIAL_POLISHED,
	[296] = VOTAN_DYEING_MATERIAL_POLISHED,
	[327] = VOTAN_DYEING_MATERIAL_POLISHED,
	[368] = VOTAN_DYEING_MATERIAL_POLISHED,
	[407] = VOTAN_DYEING_MATERIAL_POLISHED,
	[426] = VOTAN_DYEING_MATERIAL_POLISHED,
	[431] = VOTAN_DYEING_MATERIAL_POLISHED,
	[434] = VOTAN_DYEING_MATERIAL_POLISHED,
	[455] = VOTAN_DYEING_MATERIAL_POLISHED,
	[473] = VOTAN_DYEING_MATERIAL_POLISHED,
	[522] = VOTAN_DYEING_MATERIAL_POLISHED,
	[584] = VOTAN_DYEING_MATERIAL_POLISHED,
	[588] = VOTAN_DYEING_MATERIAL_POLISHED,
	[589] = VOTAN_DYEING_MATERIAL_POLISHED,
	[590] = VOTAN_DYEING_MATERIAL_POLISHED,
	[591] = VOTAN_DYEING_MATERIAL_POLISHED,
	[592] = VOTAN_DYEING_MATERIAL_POLISHED,
	[593] = VOTAN_DYEING_MATERIAL_POLISHED,
	[25] = VOTAN_DYEING_MATERIAL_METALLIC,
	[28] = VOTAN_DYEING_MATERIAL_METALLIC,
	[35] = VOTAN_DYEING_MATERIAL_METALLIC,
	[42] = VOTAN_DYEING_MATERIAL_METALLIC,
	[50] = VOTAN_DYEING_MATERIAL_METALLIC,
	[76] = VOTAN_DYEING_MATERIAL_METALLIC,
	[89] = VOTAN_DYEING_MATERIAL_METALLIC,
	[90] = VOTAN_DYEING_MATERIAL_METALLIC,
	[91] = VOTAN_DYEING_MATERIAL_METALLIC,
	[92] = VOTAN_DYEING_MATERIAL_METALLIC,
	[100] = VOTAN_DYEING_MATERIAL_METALLIC,
	[117] = VOTAN_DYEING_MATERIAL_METALLIC,
	[119] = VOTAN_DYEING_MATERIAL_METALLIC,
	[124] = VOTAN_DYEING_MATERIAL_METALLIC,
	[137] = VOTAN_DYEING_MATERIAL_METALLIC,
	[167] = VOTAN_DYEING_MATERIAL_METALLIC,
	[196] = VOTAN_DYEING_MATERIAL_METALLIC,
	[209] = VOTAN_DYEING_MATERIAL_METALLIC,
	[217] = VOTAN_DYEING_MATERIAL_METALLIC,
	[235] = VOTAN_DYEING_MATERIAL_METALLIC,
	[265] = VOTAN_DYEING_MATERIAL_METALLIC,
	[285] = VOTAN_DYEING_MATERIAL_METALLIC,
	[338] = VOTAN_DYEING_MATERIAL_METALLIC,
	[360] = VOTAN_DYEING_MATERIAL_METALLIC,
	[364] = VOTAN_DYEING_MATERIAL_METALLIC,
	[369] = VOTAN_DYEING_MATERIAL_METALLIC,
	[372] = VOTAN_DYEING_MATERIAL_METALLIC,
	[384] = VOTAN_DYEING_MATERIAL_METALLIC,
	[432] = VOTAN_DYEING_MATERIAL_METALLIC,
	[456] = VOTAN_DYEING_MATERIAL_METALLIC,
	[466] = VOTAN_DYEING_MATERIAL_METALLIC,
	[481] = VOTAN_DYEING_MATERIAL_METALLIC,
	[498] = VOTAN_DYEING_MATERIAL_METALLIC,
	[501] = VOTAN_DYEING_MATERIAL_METALLIC,
	[505] = VOTAN_DYEING_MATERIAL_METALLIC,
	[507] = VOTAN_DYEING_MATERIAL_METALLIC,
	[513] = VOTAN_DYEING_MATERIAL_METALLIC,
	[530] = VOTAN_DYEING_MATERIAL_METALLIC,
	[536] = VOTAN_DYEING_MATERIAL_METALLIC,
	[537] = VOTAN_DYEING_MATERIAL_METALLIC,
	[539] = VOTAN_DYEING_MATERIAL_METALLIC,
	[574] = VOTAN_DYEING_MATERIAL_METALLIC,
	[578] = VOTAN_DYEING_MATERIAL_METALLIC,
	[594] = VOTAN_DYEING_MATERIAL_METALLIC
}

local dyeIsDirty = true

local function UpdateDyeData()
	local self, GetDyeInfo = addon, GetDyeInfo
	local dyesByMaterialCategory = self.dyesByMaterialCategory
	for material = VOTAN_DYEING_MATERIAL_MATT, VOTAN_DYEING_MATERIAL_METALLIC do
		ZO_ClearNumericallyIndexedTable(dyesByMaterialCategory[material])
	end
	local function AddDyeInfo(dyeIndex)
		local dyeName, known, rarity, hueCategory, achievementId, r, g, b, sortKey, dyeId = GetDyeInfo(dyeIndex)
		local dyeInfo = {
			dyeId = dyeId,
			dyeName = dyeName,
			known = known,
			rarity = rarity,
			hueCategory = hueCategory,
			achievementId = achievementId,
			sortKey = sortKey,
			r = r,
			g = g,
			b = b,
			dyeIndex = dyeIndex
		}
		local materialCategory = dyeIdToMateral[dyeId] or VOTAN_DYEING_MATERIAL_UNCLASSIFIED
		table.insert(dyesByMaterialCategory[materialCategory], dyeInfo)
	end

	for dyeIndex = 1, GetNumDyes() do
		AddDyeInfo(dyeIndex)
	end
	dyeIsDirty = false
end

local function HookDyeingManager()
	local orgDirtyDyeLayout = ZO_DYEING_MANAGER.DirtyDyeLayout
	function ZO_DYEING_MANAGER.DirtyDyeLayout(...)
		dyeIsDirty = true
		return orgDirtyDyeLayout(...)
	end

	local orgGetPlayerDyesByHueCategory = ZO_DYEING_MANAGER.GetPlayerDyesByHueCategory
	-- bad hack
	function ZO_DYEING_MANAGER.GetPlayerDyesByHueCategory(...)
		local self = ...
		local sortStyleType = self:GetSortStyle()
		if sortStyleType ~= VOTAN_DYEING_SORT_STYLE_MATERIAL then
			return orgGetPlayerDyesByHueCategory(...)
		end

		if dyeIsDirty then
			UpdateDyeData()
		end

		return addon.dyesByMaterialCategory
	end
	local orgZO_DyeingUtils_GetHeaderTextFromSortType = ZO_DyeingUtils_GetHeaderTextFromSortType
	function ZO_DyeingUtils_GetHeaderTextFromSortType(...)
		local sortStyle, category = ...
		if sortStyle ~= VOTAN_DYEING_SORT_STYLE_MATERIAL then
			return orgZO_DyeingUtils_GetHeaderTextFromSortType(...)
		end
		return GetString("SI_VOTANS_IMPROVED_OUTFIT_MATERIAL", category)
	end

	local orgUpdateDyeData = ZO_DYEING_MANAGER.UpdateDyeData
	function ZO_DYEING_MANAGER.UpdateDyeData(...)
		UpdateDyeData()
		return orgUpdateDyeData(...)
	end

	local orgZO_Dyeing_CreateTooltipOnMouseEnter = ZO_Dyeing_CreateTooltipOnMouseEnter
	local function GetDyeTooltipText(swatchControl, dyeName, isDyeKnown, achievementId, nonPlayerDye, isRightAnchored)
		if swatchControl then
			local swatchObject = swatchControl.object
			if swatchObject then
				local data = swatchObject.dataSource
				if data then
					InformationTooltip:AddLine(string.format("DyeId: %i", swatchObject.dataSource.dyeId), "", ZO_NORMAL_TEXT:UnpackRGB())
				-- SLASH_COMMANDS["/zgoo"](swatchObject)
				end
			end
		end
	end
	function ZO_Dyeing_CreateTooltipOnMouseEnter(...)
		orgZO_Dyeing_CreateTooltipOnMouseEnter(...)
		return GetDyeTooltipText(...)
	end
end

local function SetSortStyle(_, _, entry)
	ZO_DYEING_MANAGER:SetSortStyle(entry.sortStyleType)
end

function addon:InitializeDyeGrouping()
	self.dyesByMaterialCategory = {}
	for material = VOTAN_DYEING_MATERIAL_MATT, VOTAN_DYEING_MATERIAL_UNCLASSIFIED do
		self.dyesByMaterialCategory[material] = {}
	end

	self.sortByMaterialEntry = ZO_ComboBox:CreateItemEntry(GetString(SI_VOTANS_IMPROVED_OUTFIT_SORT_BY_MATERIAL), SetSortStyle)
	self.sortByMaterialEntry.sortStyleType = VOTAN_DYEING_SORT_STYLE_MATERIAL

	local function addEntry()
		ZO_DYEING_KEYBOARD.sortDropDown:AddItem(self.sortByMaterialEntry, ZO_COMBOBOX_SUPRESS_UPDATE)
	end
	if ZO_DYEING_KEYBOARD.sortDropDown then
		addEntry()
	else
		SecurePostHook(ZO_DYEING_KEYBOARD, "InitializeSortsAndFilters", addEntry)
	end

	local orgUpdateOptionControls = ZO_Dyeing_Keyboard.UpdateOptionControls
	function ZO_Dyeing_Keyboard.UpdateOptionControls(...)
		local self = ...
		if ZO_DYEING_MANAGER:GetSortStyle() ~= VOTAN_DYEING_SORT_STYLE_MATERIAL then
			return orgUpdateOptionControls(...)
		end
		orgUpdateOptionControls(...)
		self.sortDropDown:SelectItem(addon.sortByMaterialEntry)
	end

	HookDyeingManager()
end
addon:InitializeDyeGrouping()
