SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45831, "Erzeugt eine <<1>> des Lebens\r\nErzeugt eine <<2>> der Lebensabsorbtion")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45832, "Erzeugt eine <<1>> der Magicka\r\nErzeugt eine <<2>> der Magickaabsorbtion")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45833, "Erzeugt eine <<1>> der Ausdauer\r\nErzeugt eine <<2>> der Ausdauerabsorbtion")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45834, "Erzeugt eine <<1>> der Lebensregeneration\r\nErzeugt eine <<2>> der Lebensminderung")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45835, "Erzeugt eine <<1>> der Magickaregeneration\r\nErzeugt eine <<2>> der Zauberkostenminderung")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45836, "Erzeugt eine <<1>> der Ausdauerregeneration\r\nErzeugt eine <<2>> der Fähigkeitenkostenminderung")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45837, "Erzeugt eine <<1>> des Gifts\r\nErzeugt eine <<2>> der Giftresistenz")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45838, "Erzeugt eine <<1>> der Flamme\r\nErzeugt eine <<2>> der Flammenresistenz")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45839, "Erzeugt eine <<1>> des Frosts\r\nErzeugt eine <<2>> der Frostresistenz")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45840, "Erzeugt eine <<1>> des Schocks\r\nErzeugt eine <<2>> der Schockresistenz")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45841, "Erzeugt eine <<1>> der Fäulnis\r\nErzeugt eine <<2>> der Seuchenresistenz")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45842, "Erzeugt eine <<1>> der Abhärtung\r\nErzeugt eine <<2>> des Zerschmetterns")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45843, "Erzeugt eine <<1>> des Waffenschadens\r\nErzeugt eine <<2>> der Schwächung")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45844, "Erzeugt eine <<1>> des ?\r\nErzeugt eine <<2>> der ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45845, "Erzeugt eine <<1>> des ?\r\nErzeugt eine <<2>> der ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45846, "Erzeugt eine <<1>> der Trankverbesserung\r\nErzeugt eine <<2>> des Tranktempos")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45847, "Erzeugt eine <<1>> des erhöhten physischen Schadens\r\nErzeugt eine <<2>> des verringerten physischen Schadens")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45848, "Erzeugt eine <<1>> des erhöhten magischen Schadens\r\nErzeugt eine <<2>> des verringerten magischen Schadens")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45849, "Erzeugt eine <<1>> des Einschlagens\r\nErzeugt eine <<2>> des Abschirmens")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH68342, "Erzeugt eine <<1>> der prismatischen Verteidigung\r\nErzeugt eine <<2>> des prismatischen Ansturms")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH166045, "Erzeugt eine <<1>> der prismatischen Regeneration\r\nErzeugt eine <<2>> des prismatischen Zauberkostenminderung")

SafeAddString(SI_RUNETOOLTIP_RUNE_SHOW_UNKNOWN, "Info für unbekannte Runen:")
SafeAddString(SI_RUNETOOLTIP_POTENCY_RUNE_SHOW_UNKNOWN, "Machtrunen")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_SHOW_UNKNOWN, "Essenzrunen")
