SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45831, "Crée un <<z:1>> vital\r\nCrée un <<z:2>> d'absorption de santé")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45832, "Crée un <<z:1>> magique\r\nCrée un <<z:2>> d'absorption de magie")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45833, "Crée un <<z:1>> vigoureux\r\nCrée un <<z:2>> d'absorption de vigueur")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45834, "Crée un <<z:1>> revivifiant\r\nCrée un <<z:2>> de réduction de santé")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45835, "Crée un <<z:1>> régénérant\r\nCrée un <<z:2>> de réduction des coûts de magie")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45836, "Crée un <<z:1>> revigorant\r\nCrée un <<z:2>> de réduction des coûts de vigueur")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45837, "Crée un <<z:1>> empoisonné\r\nCrée un <<z:2>> de résistance au poison")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45838, "Crée un <<z:1>> ardent\r\nCrée un <<z:2>> de résistance au feu")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45839, "Crée un <<z:1>> givré\r\nCrée un <<z:2>> de résistance au givre")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45840, "Crée un <<z:1>> étourdissant\r\nCrée un <<z:2>> de résistance à la foudre")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45841, "Crée un <<z:1>> odieux\r\nCrée un <<z:2>> de résistance aux maladies")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45842, "Crée un <<z:1>> robuste\r\nCrée un <<z:2>> contondant")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45843, "Crée un <<z:1>> de dégâts d'arme\r\nCrée un <<z:2>> affaiblissant")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45844, "Crée un <<z:1>> de dégâts d'arme\r\nCrée un <<z:2>> ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45845, "Crée un <<z:1>> de dégâts d'arme\r\nCrée un <<z:2>> ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45846, "Crée un <<z:1>> de l'alchimiste\r\nCrée un <<z:2>> d'accélération des potions")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45847, "Crée un <<z:1>> de puissance physique\r\nCrée un <<z:2>> de résistance physique")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45848, "Crée un <<z:1>> de puissance magique\r\nCrée un <<z:2>> de résistance magique")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45849, "Crée un <<z:1>> percutant\r\nCrée un <<z:2>> de protection")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH68342, "Crée un <<z:1>> de défense prismatique\r\nCrée un <<z:2>> d'assaut prismatique")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH166045, "Crée un <<z:1>> de régénération prismatique\r\nCrée un <<z:2>> de réduction des coûts de compétences")

SafeAddString(SI_RUNETOOLTIP_RUNE_SHOW_UNKNOWN, "Affichage des informations des runes inconnues")
SafeAddString(SI_RUNETOOLTIP_POTENCY_RUNE_SHOW_UNKNOWN, "Runes de Puissance")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_SHOW_UNKNOWN, "Runes d'Essence")