-- Translation by @snorunt361(ESOUI),@Warashi-JP(github)

SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45831, "<<z:1>> : 最大体力付呪\r\n<<z:2>> : ライフドレイン付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45832, "<<z:1>> : 最大マジカ付呪\r\n<<z:2>> : マジカ吸収付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45833, "<<z:1>> : 最大スタミナ付呪\r\n<<z:2>> : スタミナ吸収付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45834, "<<z:1>> : 体力再生付呪\r\n<<z:2>> : 体力低下付呪(オブリビオンダメージ)")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45835, "<<z:1>> : マジカ再生付呪\r\n<<z:2>> : 呪文消費減少付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45836, "<<z:1>> : スタミナ再生付呪\r\n<<z:2>> : スタミナ消費減少付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45837, "<<z:1>> : 毒の武器付呪\r\n<<z:2>> : 毒耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45838, "<<z:1>> : 炎の武器付呪\r\n<<z:2>> : 炎耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45839, "<<z:1>> : 氷の武器付呪\r\n<<z:2>> 氷結耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45840, "<<z:1>> : 雷の武器付呪\r\n<<z:2>> : 雷撃耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45841, "<<z:1>> : 汚れた武器付呪(病気ダメージ追加)\r\n<<z:2>> : 病気耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45842, "<<z:1>> : 硬化付呪\r\n(ダメージシールード展開)\r\n<<z:2>> : クラッシャー付呪\r\n(物理・呪文耐性の減少)")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45843, "<<z:1>> : 武器ダメージ付呪\r\n(武器・呪文ダメージ上昇)\r\n<<z:2>> : 弱体化付呪\r\n(武器・呪文ダメージ低下)")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45844, "Creates a <<z:1>> of weapon damage\r\nCreates a <<z:2>> of ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45845, "Creates a <<z:1>> of weapon damage\r\nCreates a <<z:2>> of ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45846, "<<z:1>> : 増幅錬金術付呪\r\n(薬の効果時間延長)\r\n<<z:2>> : 加速錬金術付呪\r\n(薬のクールダウン短縮)")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45847, "<<z:1>> : 物理攻撃強化\r\n(武器・呪文ダメージ追加＋スタミナ再生)\r\n<<z:2>> : 物理耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45848, "<<z:1>> : 魔法攻撃強化\r\n(武器・呪文ダメージ追加＋マジカ再生)\r\n <<z:2>> : 呪文耐性付呪")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45849, "<<z:1>> : 強撃付呪\r\n(強撃ダメージ追加)\r\n<<z:2>> : 身構え付呪\r\n(防御の消費減少)")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH68342, "<<z:1>> : 分光防御\r\n(最大体力・スタミナ・マジカ追加)\r\n<<z:2>> : 分光猛襲\r\n(魔法ダメージ追加＋体力・スタミナ・マジカ吸収)")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH166045, "<<z:1>> : 分光再生\r\n<<z:2>> : 分光コスト減少付呪")

SafeAddString(SI_RUNETOOLTIP_RUNE_SHOW_UNKNOWN, "不明なルーンストーン:")
SafeAddString(SI_RUNETOOLTIP_POTENCY_RUNE_SHOW_UNKNOWN, "効力ルーンストーン")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_SHOW_UNKNOWN, "本質ルーンストーン")
