SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45831, "Создаёт <<z:1>> увеличения здоровья\r\nСоздаёт <<z:2>> поглощения здоровья")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45832, "Создаёт <<z:1>> увеличения магии\r\nСоздаёт <<z:2>> поглощения магии")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45833, "Создаёт <<z:1>> увеличения запаса сил\r\nСоздаёт <<z:2>> поглощения запаса сил")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45834, "Создаёт <<z:1>> восстановления здоровья\r\nСоздаёт <<z:2>> урона Обливиона")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45835, "Создаёт <<z:1>> восстановления магии\r\nСоздаёт <<z:2>> снижения затрат магии на заклинания")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45836, "Создаёт <<z:1>> восстановления запаса сил\r\nСоздаёт <<z:2>> снижения затрат запаса сил на способности")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45837, "Создаёт <<z:1>> ядовитого урона\r\nСоздаёт <<z:2>> сопротивляемости яду")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45838, "Создаёт <<z:1>> огненного урона\r\nСоздаёт <<z:2>> сопротивляемости огню")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45839, "Создаёт <<z:1>> морозного урона\r\nСоздаёт <<z:2>> сопротивляемости морозу")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45840, "Создаёт <<z:1>> электрического урона\r\nСоздаёт <<z:2>> сопротивляемости электричеству")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45841, "Создаёт <<z:1>> болезнетворного урона\r\nСоздаёт <<z:2>> сопротивляемости болезням")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45842, "Создаёт <<z:1>> дающий щит от урона\r\nСоздаёт <<z:2>> уменьшения физической и магической сопротивляемости уели")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45843, "Создаёт <<z:1>> увеличения урона оружием и заклинаниями\r\nСоздаёт <<z:2>> уменьшения урона оружием и заклинаниями цели")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45844, "Создаёт <<z:1>> урона оружием\r\nСоздаёт <<z:2>> of ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45845, "Создаёт <<z:1>> урона оружием\r\nСоздаёт <<z:2>> of ?")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45846, "Создаёт <<z:1>> увеличения длительности зелий\r\nСоздаёт <<z:2>> снижения времени восстановления зелий")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45847, "Создаёт <<z:1>> увеличения урона оружием\r\nСоздаёт <<z:2>> физической сопротивляемости")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45848, "Создаёт <<z:1>> увеличения урона заклинаниями\r\nСоздаёт <<z:2>> магической сопротивляемости")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45849, "Создаёт <<z:1>> увеличения урона от ударов плашмя\r\nСоздаёт <<z:2>> снижения затрат на удары плашмя и блокирование")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH68342, "Создаёт <<z:1>> увеличения магии, здоровья и запаса сил\r\nСоздаёт <<z:2>> магического урона по нежити и даэдра")

SafeAddString(SI_RUNETOOLTIP_RUNE_SHOW_UNKNOWN, "Информация неизвестных рун:")
SafeAddString(SI_RUNETOOLTIP_POTENCY_RUNE_SHOW_UNKNOWN, "Руны силы")
SafeAddString(SI_RUNETOOLTIP_ESSENCE_RUNE_SHOW_UNKNOWN, "Руны сущности")
