ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45831", "Creates a <<z:1>> of health\r\nCreates a <<z:2>> of absorb health")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45832", "Creates a <<z:1>> of magicka\r\nCreates a <<z:2>> of absorb magicka")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45833", "Creates a <<z:1>> of stamina\r\nCreates a <<z:2>> of absorb stamina")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45834", "Creates a <<z:1>> of health recovery\r\nCreates a <<z:2>> of decrease health")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45835", "Creates a <<z:1>> of magicka recovery\r\nCreates a <<z:2>> of reduce spell cost")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45836", "Creates a <<z:1>> of stamina recovery\r\nCreates a <<z:2>> of reduce feat cost")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45837", "Creates a <<z:1>> of poison\r\nCreates a <<z:2>> of poison resist")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45838", "Creates a <<z:1>> of flame\r\nCreates a <<z:2>> of flame resist")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45839", "Creates a <<z:1>> of frost\r\nCreates a <<z:2>> of frost resist")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45840", "Creates a <<z:1>> of shock\r\nCreates a <<z:2>> of shock resist")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45841", "Creates a <<z:1>> of foulness\r\nCreates a <<z:2>> of disease resist")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45842", "Creates a <<z:1>> of hardening\r\nCreates a <<z:2>> of crushing")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45843", "Creates a <<z:1>> of weapon damage\r\nCreates a <<z:2>> of weakening")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45844", "Creates a <<z:1>> of weapon damage\r\nCreates a <<z:2>> of ?")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45845", "Creates a <<z:1>> of weapon damage\r\nCreates a <<z:2>> of ?")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45846", "Creates a <<z:1>> of potion boost\r\nCreates a <<z:2>> of potion speed")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45847", "Creates a <<z:1>> of increase physical harm\r\nCreates a <<z:2>> of decrease physical harm")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45848", "Creates a <<z:1>> of increase magical harm\r\nCreates a <<z:2>> of decrease spell harm")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH45849", "Creates a <<z:1>> of bashing\r\nCreates a <<z:2>> of shielding")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH68342", "Creates a <<z:1>> of prismatic defense\r\nCreates a <<z:2>> of prismatic onslaught")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_GLYPH166045", "Creates a <<z:1>> of prismatic recovery\r\nCreates a <<z:2>> of reduce skill cost")

ZO_CreateStringId("SI_RUNETOOLTIP_RUNE_SHOW_UNKNOWN", "Info for unknown Runes:")
ZO_CreateStringId("SI_RUNETOOLTIP_POTENCY_RUNE_SHOW_UNKNOWN", "Potency Runes")
ZO_CreateStringId("SI_RUNETOOLTIP_ESSENCE_RUNE_SHOW_UNKNOWN", "Essence Runes")
